version: "3.4"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - .:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx/
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
  php:
    build:
      dockerfile: .docker/Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.1'
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php
    volumes:
      - .:/var/www
    ports:
      - "${PHP_PORT}:9000"